branch-defaults:
  master:
    environment: duuit-backend-dev
  v2:
    environment: null
    group_suffix: null
global:
  application_name: duuit-backend
  branch: null
  default_ec2_keyname: aws-eb
  default_platform: Go 1 running on 64bit Amazon Linux 2
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: duuit
  repository: null
  sc: git
  workspace_type: Application
